config/routes.rb
Jobsworth::Application.routes.draw do

  resources :snippets

  resources :service_level_agreements, :only => [:create, :destroy, :update]

  resources :services, :except => [:show] do
    collection do
      get 'auto_complete_for_service_name'
    end
  end

  devise_for :users,
             :path_prefix => "auth",
             :controllers => { :sessions  => "auth/sessions", 
                                :passwords => "auth/passwords" }

  resources :users, :except => [:show]

  get 'activities/index', as: 'activities'
  root :to => 'activities#index'

  get '/unified_search' => "customers#search"
  resources :customers do
    collection do
      get 'auto_complete_for_customer_name'
    end
  end

  resources :news_items,  :except => [:show]
  resources :projects do
    get 'list_completed', :on => :collection

    member do
      get 'ajax_add_permission'
      post :complete
      post :revert
    end
  end

  # task routes
  get 'tasks/:id' => "tasks#edit", :constraints => {:id => /\d+/}
  get "tasks/view/:id" => "tasks#edit", :as => :task_view
  get "tasks/nextTasks/:count" => "tasks#nextTasks", :defaults => { :count => 5 }
  resources :tasks, :except => [:show] do
    collection do
      post 'change_task_weight'
      get  'billable'
      get 'planning'
    end
    member do
      get 'score'
      get 'clone'
    end
  end

  resources :email_addresses, :only => [:index, :update, :edit]

  resources :resources do
    collection do
      get :attributes
      get :auto_complete_for_resource_parent
    end
    get :show_password, :on => :member
  end

  resources :resource_types do
    collection do
      get :attribute
    end
  end

  resources :organizational_units

  resources :task_filters do
    get :toggle_status, :on => :member
    match :select, :on => :member
    collection do
      get :manage
      get :reset
      get :search
      get :update_current_filter
      get :set_single_task_filter
    end
  end

  resources :todos do
    match :toggle_done, :on => :member
  end

  resources :work_logs do 
    match :update_work_log, :on=> :member
  end

  resources :tags do
    collection do
      get :auto_complete_for_tags
    end
  end

  resources :work do
    collection do
      get :start
      get :stop
      get :cancel
      get :pause
      get :refresh
    end
  end

  resources :properties do
    collection do
      get :remove_property_value_dialog
      post :remove_property_value
    end
  end

  resources :scm_projects
  resources :triggers

  match 'api/scm/:provider/:secret_key' => 'scm_changesets#create'
  match ':controller/service.wsdl', :action => 'wsdl'

  resources :projects, :customers, :property_values do
    resources :score_rules
  end

  resources :milestones do
    resources :score_rules

    collection do
      get :get_milestones
    end

    member do
      post :revert
      post :complete
    end
  end

  resources :task_templates

  resources :companies do
    resources :score_rules
    collection do
      get :score_rules
      get :custom_scripts
    end
    member do
      get  :show_logo
    end
  end

  match ':controller/list' => ':controller#index'

  match ":controller(/:action(/:id(.:format)))"
end

app/controllers/resource_types_controller.rb
# encoding: UTF-8
class ResourceTypesController < ApplicationController
  before_filter :authorize_user_is_admin
  layout  "admin"

  def index
    @resource_types = current_user.company.resource_types

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @resource_types }
    end
  end

  def new
    @resource_type = ResourceType.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @resource_type }
    end
  end

  def edit
    @resource_type = current_user.company.resource_types.find(params[:id])
  end

  def create
    @resource_type = ResourceType.new(params[:resource_type])
    @resource_type.company = current_user.company

    respond_to do |format|
      if @resource_type.save
        flash[:success] = 'Resource type was successfully created.'
        format.html { redirect_to(edit_resource_type_path(@resource_type)) }
        format.xml  { render :xml => @resource_type, :status => :created, :location => @resource_type }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @resource_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @resource_type = current_user.company.resource_types.find(params[:id])

    # need to set type_attributes param when all have been deleted
    params[:resource_type][:type_attributes] ||= {}

    saved = @resource_type.update_attributes(params[:resource_type]) 
    @resource_type.company = current_user.company
    saved &&= @resource_type.save

    respond_to do |format|
      if saved
        flash[:success] = 'Resource type was successfully updated.'
        format.html { redirect_to(edit_resource_type_path(@resource_type)) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @resource_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @resource_type = current_user.company.resource_types.find(params[:id])
    @resource_type.destroy

    respond_to do |format|
      format.html { redirect_to(resource_types_url) }
      format.xml  { head :ok }
    end
  end

  def attribute
    render(:partial => "attribute", :locals => { :attribute => ResourceTypeAttribute.new })
  end
end

app/helpers/resource_types_helper.rb
# encoding: UTF-8
module ResourceTypesHelper
  ###
  # Returns the html to add an attribute to the currently shown
  # resource type.
  ###
  def add_attribute_link
    js = "appendPartial('/resource_types/attribute', '#resource_type_attributes')"
    link_to_function(_("Add another attribute"), js, :class => "add_attribute btn")
  end

end

app/views/resource_types/_attribute.html.erb
<div class="attribute resource_type_attribute" id="resource_type_attribute_<%= attribute.id %>">
  <%
     prefix = "type_attributes"
     prefix = "new_#{ prefix }" if attribute.new_record?
     prefix = "resource_type[#{ prefix }]"
   -%>

  <%= fields_for(prefix, attribute) do |f| %>
    <%= f.hidden_field(:position, :index => attribute.id, :class => "position") %>

    <div class="control-group">
      <label><%=_ "Name" %></label>
      <div class="controls">
        <%= f.text_field :name, :index => attribute.id %>
        <%= sortable_handle_tag(attribute) %>
        <%= link_to_function(_("Remove attribute"), "jQuery(this).parents('.attribute').remove()") %>
      </div>
    </div>

    <div class="control-group">
      <label><%=_ "Mandatory" %></label>
      <div class="controls">
        <%= f.check_box :is_mandatory, :index => attribute.id, :class => "nested-checkbox" %>
      </div>
    </div>

    <div class="control-group">
      <label><%=_ "This attribute is a password" %></label>
      <div class="controls">
        <%= f.check_box :is_password, :index => attribute.id, :class => "nested-checkbox" %>
      </div>
    </div>

    <div class="control-group">
      <label><%=_ "Allows multiple" %></label>
      <div class="controls">
        <%= f.check_box :allows_multiple, :index => attribute.id, :class => "nested-checkbox" %>
      </div>
    </div>

    <div class="control-group">
      <label><%=_ "Validation Regex" %></label>
      <div class="controls">
        <%= f.text_field :validation_regex, :index => attribute.id %>
      </div>
    </div>

    <div class="control-group">
      <label><%=_ "Default field length " %></label>
      <div class="controls">
        <%= f.text_field :default_field_length, :index => attribute.id %>
      </div>
    </div>

  <% end %>
</div>

app/views/resource_types/_form.html.erb
<%= form_for(@resource_type, :html => {:class => "form-horizontal"}) do |f| %>
<fieldset>
  <div class="control-group">
    <label for="resource_type_name"><%= _("Name") %></label>
    <div class="controls">
      <%= f.text_field :name %>
    </div>
  </div>

  <div class="clear">
    <legend><%= _("Attributes") %></legend>
    <div id="resource_type_attributes">
      <% @resource_type.resource_type_attributes.each do |rta| %>
        <%= render :partial => "attribute", :locals => { :attribute => rta } %>
      <% end %>
    </div>
  </div>

  <div class="form-actions">
    <%= cit_submit_tag(@resource_type) %>
    <%= add_attribute_link %>
  </div>
</fieldset>
<% end %>

app/views/resource_types/_resource_type.html.erb
<%= resource_type.name %>

app/views/resource_types/edit.html.erb
<% content_for :navigation do %>
  <%= render :partial => "companies/navigation", :locals => {:selected => "resource-type" } %>
<% end %>

<legend>Edit Resource Type</legend>

<%= render :partial => "form" %>

app/views/resource_types/index.html.erb
<% content_for :navigation do %>
  <%= render :partial => "companies/navigation", :locals => {:selected => "resource-type" } %>
<% end %>

<legend>
  Resource Types
  <%= link_to _("New resource type"), new_resource_type_path, :class => "btn pull-right" %>
</legend>

<div class="resource_types">
  <table class="table table-striped table-bordered table-condensed">
    <thead>
      <th>Name</th>
      <th>Attributes</th>
      <th></th>
      <th></th>
    </thead>
    <tbody>
      <% @resource_types.each do |rt| %>
      <tr>
	<td><%= rt.name %></td>
	<td><%= rt.resource_type_attributes.count %></td>
	<td><%= link_to _("Edit"), edit_resource_type_path(rt) %></td>
	<td><%= link_to(_("Delete"), resource_type_path(rt), :method => :delete, :confirm => "Are you sure?") %></td>  
      </tr>
      <% end %> 
    </tbody>
  </table>
</div>

app/views/resource_types/new.html.erb
<% content_for :navigation do %>
  <%= render :partial => "companies/navigation", :locals => {:selected => "resource-type" } %>
<% end %>

<legend>Create Resource Type</legend>

<%= render :partial => "form" %>