config/routes.rb
Jobsworth::Application.routes.draw do

  resources :snippets

  resources :service_level_agreements, :only => [:create, :destroy, :update]

  resources :services, :except => [:show] do
    collection do
      get 'auto_complete_for_service_name'
    end
  end

  devise_for :users,
             :path_prefix => "auth",
             :controllers => { :sessions  => "auth/sessions", 
                                :passwords => "auth/passwords" }

  resources :users, :except => [:show]

  get 'activities/index', as: 'activities'
  root :to => 'activities#index'

  get '/unified_search' => "customers#search"
  resources :customers do
    collection do
      get 'auto_complete_for_customer_name'
    end
  end

  resources :news_items,  :except => [:show]
  resources :projects do
    get 'list_completed', :on => :collection

    member do
      get 'ajax_add_permission'
      post :complete
      post :revert
    end
  end

  # task routes
  get 'tasks/:id' => "tasks#edit", :constraints => {:id => /\d+/}
  get "tasks/view/:id" => "tasks#edit", :as => :task_view
  get "tasks/nextTasks/:count" => "tasks#nextTasks", :defaults => { :count => 5 }
  resources :tasks, :except => [:show] do
    collection do
      post 'change_task_weight'
      get  'billable'
      get 'planning'
    end
    member do
      get 'score'
      get 'clone'
    end
  end

  resources :email_addresses, :only => [:index, :update, :edit]

  resources :resources do
    collection do
      get :attributes
      get :auto_complete_for_resource_parent
    end
    get :show_password, :on => :member
  end

  resources :resource_types do
    collection do
      get :attribute
    end
  end

  resources :organizational_units

  resources :task_filters do
    get :toggle_status, :on => :member
    match :select, :on => :member
    collection do
      get :manage
      get :reset
      get :search
      get :update_current_filter
      get :set_single_task_filter
    end
  end

  resources :todos do
    match :toggle_done, :on => :member
  end

  resources :work_logs do 
    match :update_work_log, :on=> :member
  end

  resources :tags do
    collection do
      get :auto_complete_for_tags
    end
  end

  resources :work do
    collection do
      get :start
      get :stop
      get :cancel
      get :pause
      get :refresh
    end
  end

  resources :properties do
    collection do
      get :remove_property_value_dialog
      post :remove_property_value
    end
  end

  resources :scm_projects
  resources :triggers

  match 'api/scm/:provider/:secret_key' => 'scm_changesets#create'
  match ':controller/service.wsdl', :action => 'wsdl'

  resources :projects, :customers, :property_values do
    resources :score_rules
  end

  resources :milestones do
    resources :score_rules

    collection do
      get :get_milestones
    end

    member do
      post :revert
      post :complete
    end
  end

  resources :task_templates

  resources :companies do
    resources :score_rules
    collection do
      get :score_rules
      get :custom_scripts
    end
    member do
      get  :show_logo
    end
  end

  match ':controller/list' => ':controller#index'

  match ":controller(/:action(/:id(.:format)))"
end

app/models/company.rb
# encoding: UTF-8
# A logical grouping of all users sharing projects
#

class Company < ActiveRecord::Base
  # Creates a score_rules association and updates the score
  # of all the task when adding a new score rule
  include Scorable

  has_attached_file :logo, :whiny => false, :styles=>{ :original => "250x50>"}, :path => File.join(Rails.root.to_s, 'store', 'logos') + "/logo_:id_:style.:extension"

  has_many      :customers, :dependent => :destroy, :order => "lower(customers.name)"
  has_many      :users, :dependent => :destroy
  has_many      :projects, :dependent => :destroy, :order => "lower(projects.name)"
  has_many      :milestones
  has_many      :tasks, :class_name => "TaskRecord"
  has_many      :templates
  has_many      :snippets, :dependent => :destroy
  has_many      :work_logs
  has_many      :project_files, :dependent => :destroy
  has_many      :tags, :dependent => :destroy, :order => 'tags.name'
  has_many      :properties, :dependent => :destroy, :include => :property_values
  has_many      :property_values, :through => :properties
  has_many      :resources, :dependent => :destroy, :order => "lower(name)"
  has_many      :resource_types, :dependent => :destroy, :order => "lower(name)"
  has_many      :custom_attributes, :dependent => :destroy
  has_many      :task_filters, :dependent => :destroy
  has_many      :statuses, :dependent => :destroy, :order => "id asc"
  has_many      :wiki_pages, :dependent => :destroy
  has_many      :triggers, :dependent => :destroy
  has_many      :services, :dependent => :destroy
  has_many      :service_level_agreements, :dependent => :destroy
  has_many      :news_items, :dependent => :destroy
  has_many      :email_addresses

  has_many      :preferences, :as => :preferencable
  include PreferenceMethods

#  validates_format_of :contact_email, :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/
#  validates_length_of :contact_name,  :in=>3..200
  validates_length_of           :name,  :maximum=>200
  validates_presence_of         :name
  validates_presence_of         :subdomain
  validates_uniqueness_of       :subdomain

  after_create :create_default_properties
  after_create :create_default_statuses

  ###
  # Creates the default properties used for describing tasks.
  # Returns an array of the created properties.
  ###
  def create_default_properties
    new_props = []
    Property.defaults.each do |property_params, property_values_params|
      name = property_params[:name]
      existing = properties.detect { |p| p.name == name }

      if !existing
        p = properties.new(property_params)
        p.property_values.build(property_values_params)
        p.save!
        new_props << p
      else
        new_props << existing
      end
    end

    self.properties.reload
    return new_props
  end

  # Creates the default statuses for this company
  def create_default_statuses
    Status.create_default_statuses(self)
  end

  def suppressed_emails
    self.suppressed_email_addresses.blank? ? [] : self.suppressed_email_addresses.split(/,|\n/).collect {|e| e.strip }
  end

  ###
  # Sorts the given tasks in the default sort order.
  # Default sorting uses the completed at time, the due date, task num and any
  # custom properties with the default_sort parameter.
  ###
  def sort(tasks)
    res = tasks.sort_by do |task|
      array = []
      array << -task.completed_at.to_i
      array << rank_by_properties(task)
      array << - (task.due_date || 9999999999).to_i
      array << - task.task_num
    end
    res = res.reverse

    return res
  end

  ###
  # Returns an array of properties that should be used for sorting tasks.
  ###
  def sort_properties
    properties.select { |p| p.default_sort }
  end

  ###
  # Returns the maximum sort rank a task could possibly have.
  ###
  def maximum_sort_rank
    @maximum_sort_rank ||= sort_properties.inject(0) { |rank, property| rank += property.property_values.length }
  end

  ###
  # Returns an int to to use to rank the task according to properties
  # set up as default_sort.
  ###
  def rank_by_properties(task)
    rank_by_properties = sort_properties.inject(0) do |rank, property|
      pv = task.property_value(property)
      rank ||= 0 # for some reason rank is nil occasionally in tests.

      if pv
        rank += (pv.sort_rank || 0)
      end
    end

    return (rank_by_properties || 0)
  end

  ###
  # Returns the property to use to represent a tasks type.
  ###
  def type_property
    @type_property ||= properties.detect { |p| p.name == "Type" || p.name == _("Type") }
  end

  ###
  # Returns the URL to the installation
  ###
  def site_URL
    if $CONFIG[:SSL]
      url = "https://"
    else
      url = "http://"
    end
    url += subdomain + "." + $CONFIG[:domain]
  end

  # Returns a list of property values which should be considered
  # as marking tasks as critical priority
  def critical_values
    @critical_values ||= sort_properties.inject([]) do |res, prop|
      range = (prop.property_values.count / 3).to_i
      res += prop.property_values[0, range]
    end
  end

  # Returns a list of property values which should be considered
  # as marking tasks as normal priority
  def normal_values
    @normal_values ||= sort_properties.inject([]) do |res, prop|
      res += prop.property_values.select do |pv|
        !critical_values.index(pv) and !low_values.index(pv)
      end
    end
  end

  # Returns a list of property values which should be considered
  # as marking tasks as low priority
  def low_values
    @low_values ||= sort_properties.inject([]) do |res, prop|
      length = prop.property_values.count
      range = length - (length / 3).to_i
      res += prop.property_values[range, length]
    end
  end

  # Find the Internal client of this company.
  # A small kludge is needed,as it was previously called Internal, now it has the same
  # name as the parent company.
  def internal_customer
    conds = ["(name = ? OR name = 'Internal') AND company_id = ? ", self.name, self.id]
    @internal_customer ||= customers.where(conds).order('id').first
  end

  def logo_path
    logo.path
  end

  def logo?
    !self.logo_path.nil? && File.exist?(self.logo_path)
  end

end




# == Schema Information
#
# Table name: companies
#
#  id                         :integer(4)      not null, primary key
#  name                       :string(200)     default(""), not null
#  contact_email              :string(200)
#  contact_name               :string(200)
#  created_at                 :datetime
#  updated_at                 :datetime
#  subdomain                  :string(255)     default(""), not null
#  show_wiki                  :boolean(1)      default(TRUE)
#  suppressed_email_addresses :text
#  logo_file_name             :string(255)
#  logo_content_type          :string(255)
#  logo_file_size             :integer(4)
#  logo_updated_at            :datetime
#
# Indexes
#
#  index_companies_on_subdomain  (subdomain) UNIQUE
#

app/controllers/companies_controller.rb
# encoding: UTF-8
class CompaniesController < ApplicationController
  before_filter :authorize_user_is_admin, :except => [:show_logo]

  layout 'admin'

  def edit
    @company = current_user.company
  end

  def score_rules
    @company = current_user.company
  end

  def custom_scripts
    @company = current_user.company
  end

  def update
    @company = current_user.company

    #TODO: When refactoring the model, remove this whole 'internal_customer' thingy,
    # as far as I can tell, the internal customer is only used for storing the 
    # company logo.
    @internal = @company.internal_customer
    if @internal.nil?
      flash[:error] = 'Unable to find internal customer.'
      render :action => 'edit'
      return
    end

    if @company.update_attributes(params[:company])
      @internal.name = @company.name
      @internal.save

      flash[:success] = _('Company settings updated')
      redirect_from_last
    else
      flash[:error] = @company.errors.full_messages.join(". ")
      render :action => 'edit'
    end
  end

  # Show a company logo
  def show_logo
    company = Company.find(params[:id])

    if company.logo?
      send_file(company.logo_path, :filename => "logo", :disposition => "inline", :type => company.logo_content_type)
    else
      render :nothing => true
    end
  end

end

app/helpers/companies_helper.rb
# encoding: UTF-8
module CompaniesHelper

  # A select tag to choose the company's default incoming email
  # location.
  def incoming_email_select_tag
    pref_name = "incoming_email_project"
    name = "company[preference_attributes][#{ pref_name }]"
    options = [ "" ] + objects_to_names_and_ids(@company.projects)
    options = options_for_select(options, :selected => @company.preference(pref_name).to_i)

    return select_tag(name, options)
  end

  # Returns an array of file names for custom scripts stored in the
  # lib/scripts dir
  def all_custom_scripts
    Dir.glob("#{Rails.root}/lib/scripts/*.rb").map { |f| File.basename(f) }
  end
end

app/views/companies/_navigation.html.erb
<div class="well" style="padding: 8px 0;">
  <% scripts = all_custom_scripts -%>
  <ul class="nav nav-list">
    <li class="nav-header">
      Admin Panel
    </li>
    <li class="<%= active_class(selected, "general") %>">
      <a href="<%= edit_company_path(current_user.company) %>">General</a>
    </li>
    <li class="<%= active_class(selected, "score-rules") %>">
      <a href="/companies/score_rules">Score Rules</a>
    </li>
    <% if scripts.size > 0 %>
      <li class="<%= active_class(selected, "custom-scripts") %>">
        <a href="/companies/custom_scripts">Custom Scripts</a>
      </li>
    <% end %>
    <li class="<%= active_class(selected, "templates") %>">
      <%= link_to _("Templates"), :controller => 'task_templates', :action=>'index' %>
    </li>
    <li class="<%= active_class(selected, "triggers") %>">
      <%= link_to _("Triggers"), :controller => 'triggers' %>
    </li>
    <li class="<%= active_class(selected, "services") %>">
      <%= link_to _("Services"), services_path %>
    </li>
    <li class="<%= active_class(selected, "news-items") %>">
      <%= link_to _("News Items"), news_items_path %>
    </li>
    <li class="<%= active_class(selected, "snippets") %>">
      <%= link_to _("Snippets"), snippets_path %>
    </li>
    <li class="<%= active_class(selected, "orphaned-emails") %>">
      <%= link_to _("Orphaned Emails"), email_addresses_path %>
    </li>
    <li class="divider"></li>
    <li class="nav-header">
      Properties
    </li>
    <li class="<%= active_class(selected, "users-properties") %>">
      <a href="/custom_attributes/edit?type=User">Person</a>
    </li>
    <li class="<%= active_class(selected, "customers-properties") %>">
      <a href="/custom_attributes/edit?type=Customer">Company</a>
    </li>
    <li class="<%= active_class(selected, "organizational-units-properties") %>">
      <a href="/custom_attributes/edit?type=OrganizationalUnit">Company Location</a>
    </li>
    <li class="<%= active_class(selected, "work-logs-properties") %>">
      <a href="/custom_attributes/edit?type=WorkLog">Work Log</a>
    </li>
    <li class="<%= active_class(selected, "task-properties") %>">
      <a href="<%= properties_path %>">Task</a>
    </li>
    <li class="<%= active_class(selected, "resource-type") %>">
      <a href="<%= resource_types_path  %>">Resource Types</a>
    </li>
  </ul>
</div>

app/views/companies/_settings.html.erb
<div class="control-group">
  <label for="company_name"><%=_ 'Company Name' %></label>
  <div class="controls">
    <%= text_field 'company', 'name' %>
  </div>
</div>

<div class="control-group">
  <label for="company_show_wiki"><%=_ 'Use Wiki' %></label>
  <div class="controls">
    <%= check_box 'company', 'show_wiki' %>
  </div>
</div>

<div class="control-group">
  <label for="company_suppressed_email_addresses"><%= _('Suppressed email addresses') %></label>
  <div class="controls">
    <%= text_area 'company', 'suppressed_email_addresses', :rows => 5, :class => "input-xxlarge" %>
    <div class="optional"><%=_ "(seperate emails by comma or new line)" %></div>
  </div>
</div>

<div class="control-group">
  <label for="incoming_email_project" rel="tooltip" title="<%=_ 'Emails received by Jobsworth that don\'t belong to a task will be added to this project' %>" data-placement="right">
    <%=_ "Incoming Email Project" %>
  </label>
  <div class="controls">
    <%= incoming_email_select_tag %>
  </div>
</div>

<% if current_user.company.logo? -%>
  <div class="control-group">
    <label><%=_ 'Current logo' %></label>
    <div class="controls">
      <%= tag("img", {:src => "/companies/show_logo/#{current_user.company.id}", :border => 0 } ) %>
    </div>
  </div>
<% end -%>

<div class="control-group">
  <label><%=_ 'New Logo' %></label>
  <div class="controls">
    <%= file_field :company, :logo %>
    <div class="optional"><%=_ "(250x50px should look good. The logo will be shown up top instead of the Jobsworth one, and on your login page.)" %></div>
  </div>
</div>

app/views/companies/custom_scripts.html.erb
<% @page_title = "Score Rules - #{$CONFIG[:productName]}" %>

<% content_for :navigation do %>
  <%= render :partial => "companies/navigation", :locals => {:selected => "custom-scripts"} %>
<% end %>

<legend>Custom Scripts</legend>

<p class="alert alert-info">
  <%=_ "Custom ruby scripts can be placed in the lib/scripts directory. They will then be listed below and can be executed against the current Jobsworth database." %>
</p>

<% scripts = all_custom_scripts -%>

<% if scripts and scripts.any? -%>
  <ul>
    <% scripts.each do |script| -%>
    <li>
	<%= link_to script, :controller => "scripts", :script => script %>
    </li>
    <% end -%>
  </ul>
<% else -%>
  <p>
    <%=_ ("No custom scripts found. If there should be some, check the file ends in \".rb\" and is in the folder: #{Rails.root}/lib/scripts") %>
  </p>
<% end -%>

app/views/companies/edit.html.erb
<% @page_title = "Company Setting - #{$CONFIG[:productName]}" %>

<% content_for :navigation do %>
  <%= render :partial => "companies/navigation", :locals => {:selected => "general"} %>
<% end %>

<legend><%=_ 'Company Settings' %></legend>

<%= form_for(@company, :html => {:class => "form-horizontal", :multipart => true}) do %>
  <%= render :partial => "settings" %>
  <div class="form-actions">
    <%= submit_tag _("Save"), :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/companies/score_rules.html.erb
<% @page_title = "Score Rules - #{$CONFIG[:productName]}" %>

<% content_for :navigation do %>
  <%= render :partial => "companies/navigation", :locals => {:selected => "score-rules"} %>
<% end %>

<legend><%=_ 'Score Rules' %></legend>

<%= render 'shared/score_rules_container',
           :container_name => 'companies',
           :container_id   => @company.id %>